export const urlTrailer = "https://project-13-back.vercel.app/api/v1/movies/"
export const urlGif = "https://project-13-back.vercel.app/api/v1/platforms/name/"
export const urlPlatforms = "https://project-13-back.vercel.app/api/v1/platforms"
export const urlMovieById = "https://project-13-back.vercel.app/api/v1/movies/"
export const urlMoviesByPlatformAndCategory = "https://project-13-back.vercel.app/api/v1/movies/search/*/"
export const urlMoviesbyName = "https://project-13-back.vercel.app/api/v1/movies/search/"
export const urlUserInfo = "https://project-13-back.vercel.app/api/v1/users/"
export const urlDeleteSeenMovie = "https://project-13-back.vercel.app/api/v1/users/remove-seenMovies/"
export const urlLogin = "https://project-13-back.vercel.app/api/v1/users/login"
export const urlRegister ="https://project-13-back.vercel.app/api/v1/users/register"

export const BASE_URL = ""
